package PA;

import java.io.*;
import java.net.*;

public class ModuloRemoto extends javax.swing.JFrame {
    private Socket socket;
    private PrintWriter out;
    private BufferedReader in;
    private String servidorIP = "localhost";
    private int puerto = 8080;
    
    public ModuloRemoto() {
        initComponents();
        conectar();
        iniciarActualizador();
    }
    
    private void conectar() {
        try {
            socket = new Socket(servidorIP, puerto);
            out = new PrintWriter(socket.getOutputStream(), true);
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            System.out.println("Conectado al servidor");
        } catch (IOException e) {
            System.out.println("ERROR: No se pudo conectar al servidor");
        }
    }
    
    private void iniciarActualizador() {
        new Thread(() -> {
            while (true) {
                try {
                    Thread.sleep(1000);
                    actualizarTodo();
                } catch (InterruptedException e) {}
            }
        }).start();
    }
    
    private void actualizarTodo() {
        if (out == null) return;
        
        DemogorgonDelMes();
        actualizarEvento();
    }
    
    private void enviarComando(String comando) {
        if (out != null) {
            out.println(comando);
            actualizarTodo();
        }
    }
    
    // Acciones para botones
    public void pausar() { enviarComando("PAUSAR"); }
    public void reanudar() { enviarComando("REANUDAR"); }
    
    private boolean pausado = false;
    
    private void togglePausa() {
        if (out != null) {
            if (pausado) {
                out.println("REANUDAR");
                btnPausa.setText("Reanudar");
            } else {
                out.println("PAUSAR");
                btnPausa.setText("Pausar");
            }
            pausado = !pausado;
        } else {
            System.out.println("No conectado al servidor");
        }
    }
    
    private void DemogorgonDelMes() {
        if (out == null) return;
        out.println("RANKING");
        try {
            StringBuilder sb = new StringBuilder();
            String linea;
            // Leer hasta línea vacía (fin del mensaje)
            while ((linea = in.readLine()) != null) {
                if (linea.isEmpty()) break;
                sb.append(linea).append("\n");
            }
            txtRanking.setText(sb.toString());
        } catch (IOException e) {
            txtRanking.setText("Error al obtener ranking");
        }
    }
    
    private void actualizarEvento() {
        if (out == null) return;
        out.println("EVENTO");
        try {
            String linea = in.readLine();
            if (linea != null && !linea.isEmpty()) {
                String[] partes = linea.split("\\|");
                String tipoEvento = partes[0];
                String tiempoRestante = partes[1];

                if (tipoEvento.equals("NINGUNO")) {
                    lblEventoActual.setText("Evento: Sin evento activo");
                    lblTiempoEvento.setText("Tiempo restante: --");
                } else {
                    String nombreLegible = "";
                    switch (tipoEvento) {
                        case "APAGÓN": nombreLegible = "Apagón del Laboratorio"; break;
                        case "TORMENTA": nombreLegible = "Tormenta del Upside Down"; break;
                        case "ELEVEN": nombreLegible = "Intervención de Eleven"; break;
                        case "RED_MENTAL": nombreLegible = "Red Mental"; break;
                    }
                    lblEventoActual.setText("Evento: " + nombreLegible);
                    lblTiempoEvento.setText("Tiempo restante: " + tiempoRestante + "s");
                }
            }
        } catch (IOException e) {
            lblEventoActual.setText("Evento: Error de conexión");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        PanelResumenHawkins = new javax.swing.JPanel();
        lblTituloResumenHawkins = new javax.swing.JLabel();
        lblEstadoHawkins = new javax.swing.JLabel();
        PanelEstadoPortales = new javax.swing.JPanel();
        lblTituloEstadoPortales = new javax.swing.JLabel();
        jScrollEstadoPortales = new javax.swing.JScrollPane();
        txtEstadoPortales = new javax.swing.JTextArea();
        PanelEstadoUD = new javax.swing.JPanel();
        lblTituloEstadoUD = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEstadoUDNinos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEstadoUDDemogorgones = new javax.swing.JTextArea();
        PanelRankingDemogorgones = new javax.swing.JPanel();
        ScrollPanelRanking = new javax.swing.JScrollPane();
        txtRanking = new javax.swing.JTextArea();
        lblRanking = new javax.swing.JLabel();
        PanelEvento = new javax.swing.JPanel();
        lblEvento = new javax.swing.JLabel();
        lblEventoActual = new javax.swing.JLabel();
        lblTiempoEvento = new javax.swing.JLabel();
        LabelModuloRemoto = new javax.swing.JLabel();
        btnPausa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelGeneral.setBackground(new java.awt.Color(102, 102, 102));

        PanelResumenHawkins.setBackground(new java.awt.Color(153, 153, 153));

        lblTituloResumenHawkins.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTituloResumenHawkins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloResumenHawkins.setText("Resumen Hawkins");

        lblEstadoHawkins.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoHawkins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoHawkins.setText("Total Niños en Hawkins: [/n]");

        javax.swing.GroupLayout PanelResumenHawkinsLayout = new javax.swing.GroupLayout(PanelResumenHawkins);
        PanelResumenHawkins.setLayout(PanelResumenHawkinsLayout);
        PanelResumenHawkinsLayout.setHorizontalGroup(
            PanelResumenHawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResumenHawkinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelResumenHawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloResumenHawkins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstadoHawkins, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelResumenHawkinsLayout.setVerticalGroup(
            PanelResumenHawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResumenHawkinsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloResumenHawkins, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstadoHawkins, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelEstadoPortales.setBackground(new java.awt.Color(153, 153, 153));

        lblTituloEstadoPortales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTituloEstadoPortales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloEstadoPortales.setText("Estado de Portales");

        txtEstadoPortales.setBackground(new java.awt.Color(204, 204, 204));
        txtEstadoPortales.setColumns(10);
        txtEstadoPortales.setRows(5);
        jScrollEstadoPortales.setViewportView(txtEstadoPortales);

        javax.swing.GroupLayout PanelEstadoPortalesLayout = new javax.swing.GroupLayout(PanelEstadoPortales);
        PanelEstadoPortales.setLayout(PanelEstadoPortalesLayout);
        PanelEstadoPortalesLayout.setHorizontalGroup(
            PanelEstadoPortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadoPortalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstadoPortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloEstadoPortales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollEstadoPortales))
                .addContainerGap())
        );
        PanelEstadoPortalesLayout.setVerticalGroup(
            PanelEstadoPortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadoPortalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloEstadoPortales, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollEstadoPortales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        PanelEstadoUD.setBackground(new java.awt.Color(153, 153, 153));

        lblTituloEstadoUD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTituloEstadoUD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloEstadoUD.setText("Ubicaciónes Upside Down");

        txtEstadoUDNinos.setBackground(new java.awt.Color(204, 204, 204));
        txtEstadoUDNinos.setColumns(10);
        txtEstadoUDNinos.setRows(5);
        jScrollPane1.setViewportView(txtEstadoUDNinos);

        txtEstadoUDDemogorgones.setBackground(new java.awt.Color(204, 204, 204));
        txtEstadoUDDemogorgones.setColumns(10);
        txtEstadoUDDemogorgones.setRows(5);
        jScrollPane2.setViewportView(txtEstadoUDDemogorgones);

        javax.swing.GroupLayout PanelEstadoUDLayout = new javax.swing.GroupLayout(PanelEstadoUD);
        PanelEstadoUD.setLayout(PanelEstadoUDLayout);
        PanelEstadoUDLayout.setHorizontalGroup(
            PanelEstadoUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadoUDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstadoUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloEstadoUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelEstadoUDLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelEstadoUDLayout.setVerticalGroup(
            PanelEstadoUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadoUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloEstadoUD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEstadoUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        PanelRankingDemogorgones.setBackground(new java.awt.Color(153, 153, 153));

        txtRanking.setBackground(new java.awt.Color(204, 204, 204));
        txtRanking.setColumns(10);
        txtRanking.setRows(5);
        ScrollPanelRanking.setViewportView(txtRanking);

        lblRanking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRanking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRanking.setText("Ranking Demogorgones");

        javax.swing.GroupLayout PanelRankingDemogorgonesLayout = new javax.swing.GroupLayout(PanelRankingDemogorgones);
        PanelRankingDemogorgones.setLayout(PanelRankingDemogorgonesLayout);
        PanelRankingDemogorgonesLayout.setHorizontalGroup(
            PanelRankingDemogorgonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRankingDemogorgonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRankingDemogorgonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPanelRanking)
                    .addComponent(lblRanking, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelRankingDemogorgonesLayout.setVerticalGroup(
            PanelRankingDemogorgonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRankingDemogorgonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRanking, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPanelRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelEvento.setBackground(new java.awt.Color(153, 153, 153));

        lblEvento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEvento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEvento.setText("Evento Activo");

        lblEventoActual.setBackground(new java.awt.Color(255, 255, 255));
        lblEventoActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEventoActual.setText("SIN INICIALIZAR");

        lblTiempoEvento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTiempoEvento.setText("SIN INICIALIZAR");

        javax.swing.GroupLayout PanelEventoLayout = new javax.swing.GroupLayout(PanelEvento);
        PanelEvento.setLayout(PanelEventoLayout);
        PanelEventoLayout.setHorizontalGroup(
            PanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTiempoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEventoActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelEventoLayout.setVerticalGroup(
            PanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEventoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTiempoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        LabelModuloRemoto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelModuloRemoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelModuloRemoto.setText("Modulo Remoto");

        btnPausa.setBackground(new java.awt.Color(204, 0, 0));
        btnPausa.setForeground(new java.awt.Color(255, 255, 255));
        btnPausa.setText("Pausar");
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelEstadoPortales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelResumenHawkins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPausa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelEstadoUD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelModuloRemoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelRankingDemogorgones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGeneralLayout.createSequentialGroup()
                        .addComponent(LabelModuloRemoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelEstadoUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGeneralLayout.createSequentialGroup()
                        .addComponent(PanelRankingDemogorgones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addComponent(PanelResumenHawkins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelEstadoPortales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        togglePausa();
    }//GEN-LAST:event_btnPausaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloRemoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelModuloRemoto;
    private javax.swing.JPanel PanelEstadoPortales;
    private javax.swing.JPanel PanelEstadoUD;
    private javax.swing.JPanel PanelEvento;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelRankingDemogorgones;
    private javax.swing.JPanel PanelResumenHawkins;
    private javax.swing.JScrollPane ScrollPanelRanking;
    private javax.swing.JButton btnPausa;
    private javax.swing.JScrollPane jScrollEstadoPortales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEstadoHawkins;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblEventoActual;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JLabel lblTiempoEvento;
    private javax.swing.JLabel lblTituloEstadoPortales;
    private javax.swing.JLabel lblTituloEstadoUD;
    private javax.swing.JLabel lblTituloResumenHawkins;
    private javax.swing.JTextArea txtEstadoPortales;
    private javax.swing.JTextArea txtEstadoUDDemogorgones;
    private javax.swing.JTextArea txtEstadoUDNinos;
    private javax.swing.JTextArea txtRanking;
    // End of variables declaration//GEN-END:variables
}
