package PA;

import java.io.*;
import java.net.*;

public class ModuloRemoto extends javax.swing.JFrame {
    private Socket socket;
    private PrintWriter out;
    private BufferedReader in;
    private String servidorIP = "localhost";
    private int puerto = 8080;
    
    public ModuloRemoto() {
        initComponents();
        conectar();
        iniciarActualizador();
    }
    
    private void conectar() {
        try {
            socket = new Socket(servidorIP, puerto);
            out = new PrintWriter(socket.getOutputStream(), true);
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            System.out.println("Conectado al servidor");
        } catch (IOException e) {
            System.out.println("ERROR: No se pudo conectar al servidor");
        }
    }
    
    private void iniciarActualizador() {
        new Thread(() -> {
            while (true) {
                try {
                    Thread.sleep(1000);
                    actualizarEstado();
                } catch (InterruptedException e) {}
            }
        }).start();
    }
    
    private void actualizarEstado() {
        if (out == null) return;
        out.println("ESTADO");
        try {
            StringBuilder sb = new StringBuilder();
            String linea;
            while ((linea = in.readLine()) != null) {
                if (linea.isEmpty()) break;
                sb.append(linea).append("\n");
            }
            // Actualizar tu área de texto
            // areaEstado.setText(sb.toString());
        } catch (IOException e) {}
    }
    
    private void enviarComando(String comando) {
        if (out != null) {
            out.println(comando);
            actualizarEstado();
        }
    }
    
    // Acciones para botones
    public void pausar() { enviarComando("PAUSAR"); }
    public void reanudar() { enviarComando("REANUDAR"); }
    
    private boolean pausado = false;
    
    private void togglePausa() {
        if (out != null) {
            if (pausado) {
                out.println("REANUDAR");
                btnPausa.setText("Reanudar");
            } else {
                out.println("PAUSAR");
                btnPausa.setText("Pausar");
            }
            pausado = !pausado;
        } else {
            System.out.println("No conectado al servidor");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        PanelResumenHawkins = new javax.swing.JPanel();
        PanelEstadoPortales = new javax.swing.JPanel();
        PanelEstadoUD = new javax.swing.JPanel();
        PanelRankingDemogorgones = new javax.swing.JPanel();
        PanelEvento = new javax.swing.JPanel();
        LabelModuloRemoto = new javax.swing.JLabel();
        btnPausa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelGeneral.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout PanelResumenHawkinsLayout = new javax.swing.GroupLayout(PanelResumenHawkins);
        PanelResumenHawkins.setLayout(PanelResumenHawkinsLayout);
        PanelResumenHawkinsLayout.setHorizontalGroup(
            PanelResumenHawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        PanelResumenHawkinsLayout.setVerticalGroup(
            PanelResumenHawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelEstadoPortalesLayout = new javax.swing.GroupLayout(PanelEstadoPortales);
        PanelEstadoPortales.setLayout(PanelEstadoPortalesLayout);
        PanelEstadoPortalesLayout.setHorizontalGroup(
            PanelEstadoPortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelEstadoPortalesLayout.setVerticalGroup(
            PanelEstadoPortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelEstadoUDLayout = new javax.swing.GroupLayout(PanelEstadoUD);
        PanelEstadoUD.setLayout(PanelEstadoUDLayout);
        PanelEstadoUDLayout.setHorizontalGroup(
            PanelEstadoUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelEstadoUDLayout.setVerticalGroup(
            PanelEstadoUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelRankingDemogorgonesLayout = new javax.swing.GroupLayout(PanelRankingDemogorgones);
        PanelRankingDemogorgones.setLayout(PanelRankingDemogorgonesLayout);
        PanelRankingDemogorgonesLayout.setHorizontalGroup(
            PanelRankingDemogorgonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        PanelRankingDemogorgonesLayout.setVerticalGroup(
            PanelRankingDemogorgonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelEventoLayout = new javax.swing.GroupLayout(PanelEvento);
        PanelEvento.setLayout(PanelEventoLayout);
        PanelEventoLayout.setHorizontalGroup(
            PanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelEventoLayout.setVerticalGroup(
            PanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        LabelModuloRemoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelModuloRemoto.setText("Modulo Remoto");

        btnPausa.setBackground(new java.awt.Color(204, 0, 0));
        btnPausa.setForeground(new java.awt.Color(255, 255, 255));
        btnPausa.setText("Pausar");
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelEstadoPortales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelResumenHawkins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PanelEstadoUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelModuloRemoto, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addComponent(btnPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelRankingDemogorgones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGeneralLayout.createSequentialGroup()
                        .addComponent(LabelModuloRemoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelEstadoUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addComponent(PanelRankingDemogorgones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addComponent(PanelResumenHawkins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelEstadoPortales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        togglePausa();
    }//GEN-LAST:event_btnPausaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloRemoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelModuloRemoto;
    private javax.swing.JPanel PanelEstadoPortales;
    private javax.swing.JPanel PanelEstadoUD;
    private javax.swing.JPanel PanelEvento;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelRankingDemogorgones;
    private javax.swing.JPanel PanelResumenHawkins;
    private javax.swing.JButton btnPausa;
    // End of variables declaration//GEN-END:variables
}
